- name: condtions playbook
  hosts: localhost
  become: true
  tasks:
    - name: course name
      ansible.builtin.debug:
        msg: devops course
      when: course_name == "devops"

    - name: course name
      ansible.builtin.debug:
        msg: aws course
      when: course_name == "aws"
