- name: setup facts
  hosts: localhost
  become: true
  tasks:
    - name: ansible_default_ipv4.address
      ansible.built.debug:
        msg: "The IP of this host is {{ ansible_default_ipv4.address }}"